import { CardToken, DevelopmentCard, NobleCard } from './classes';

export const NOBLE_CARDS: NobleCard[] = [
  new NobleCard(1, 'Mary, Queen of Scots', 3, new CardToken({ red: 4, green: 4 })),
  new NobleCard(2, 'Charles V', 3, new CardToken({ red: 3, white: 3, black: 3 })),
  new NobleCard(3, 'Machiavelli', 3, new CardToken({ blue: 4, white: 4 })),
  new NobleCard(4, 'Isabella I', 3, new CardToken({ white: 4, black: 4 })),
  new NobleCard(5, 'Suleiman the Magnificent', 3, new CardToken({ green: 4, blue: 4 })),
  new NobleCard(6, 'Catherine de Medici', 3, new CardToken({ red: 3, green: 3, blue: 3 })),
  new NobleCard(7, 'Anne of Brittany', 3, new CardToken({ green: 3, blue: 3, white: 3 })),
  new NobleCard(8, 'Henry VIII', 3, new CardToken({ red: 4, black: 4 })),
  new NobleCard(9, 'Elisabeth of Austria', 3, new CardToken({ blue: 3, white: 3, black: 3 })),
  new NobleCard(10, 'Francis I', 3, new CardToken({ red: 3, green: 3, black: 3 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_1: DevelopmentCard[] = [
  new DevelopmentCard(1, 'CARD_OF_LEVEL_1_1', 1, 0, new CardToken({ blue: 1 }), new CardToken({ red: 1 })),
  new DevelopmentCard(2, 'CARD_OF_LEVEL_1_2', 1, 0, new CardToken({ green: 2 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(3, 'CARD_OF_LEVEL_1_3', 1, 0, new CardToken({ red: 2 }), new CardToken({ white: 1 })),
  new DevelopmentCard(4, 'CARD_OF_LEVEL_1_4', 1, 0, new CardToken({ black: 2 }), new CardToken({ green: 1 })),
  new DevelopmentCard(5, 'CARD_OF_LEVEL_1_5', 1, 0, new CardToken({ white: 1, green: 1 }), new CardToken({ black: 1 })),
  new DevelopmentCard(6, 'CARD_OF_LEVEL_1_6', 1, 0, new CardToken({ red: 1, black: 1 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(7, 'CARD_OF_LEVEL_1_7', 1, 0, new CardToken({ green: 1, black: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(8, 'CARD_OF_LEVEL_1_8', 1, 0, new CardToken({ red: 1, blue: 1 }), new CardToken({ green: 1 })),
  new DevelopmentCard(9, 'CARD_OF_LEVEL_1_9', 1, 0, new CardToken({ blue: 2, green: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(10, 'CARD_OF_LEVEL_1_10', 1, 1, new CardToken({ black: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(11, 'CARD_OF_LEVEL_1_11', 1, 0, new CardToken({ blue: 1, red: 1 }), new CardToken({ green: 1 })),
  new DevelopmentCard(12, 'CARD_OF_LEVEL_1_12', 1, 0, new CardToken({ green: 1, white: 1 }), new CardToken({ black: 1 })),
  new DevelopmentCard(13, 'CARD_OF_LEVEL_1_13', 1, 0, new CardToken({ black: 1, green: 2 }), new CardToken({ red: 1 })),
  new DevelopmentCard(14, 'CARD_OF_LEVEL_1_14', 1, 0, new CardToken({ blue: 1, green: 1 }), new CardToken({ red: 1 })),
  new DevelopmentCard(15, 'CARD_OF_LEVEL_1_15', 1, 1, new CardToken({ blue: 4 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(16, 'CARD_OF_LEVEL_1_16', 1, 1, new CardToken({ green: 4 }), new CardToken({ green: 1 })),
  new DevelopmentCard(17, 'CARD_OF_LEVEL_1_17', 1, 0, new CardToken({ red: 2, green: 1 }), new CardToken({ black: 1 })),
  new DevelopmentCard(18, 'CARD_OF_LEVEL_1_18', 1, 0, new CardToken({ blue: 1, green: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(19, 'CARD_OF_LEVEL_1_19', 1, 1, new CardToken({ red: 4 }), new CardToken({ red: 1 })),
  new DevelopmentCard(20, 'CARD_OF_LEVEL_1_20', 1, 1, new CardToken({ white: 4 }), new CardToken({ white: 1 })),
  new DevelopmentCard(21, 'CARD_OF_LEVEL_1_21', 1, 0, new CardToken({ black: 1, blue: 1 }), new CardToken({ red: 1 })),
  new DevelopmentCard(22, 'CARD_OF_LEVEL_1_22', 1, 0, new CardToken({ white: 1, red: 2 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(23, 'CARD_OF_LEVEL_1_23', 1, 0, new CardToken({ green: 2, black: 1 }), new CardToken({ black: 1 })),
  new DevelopmentCard(24, 'CARD_OF_LEVEL_1_24', 1, 0, new CardToken({ blue: 2, red: 1 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(25, 'CARD_OF_LEVEL_1_25', 1, 0, new CardToken({ green: 2, red: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(26, 'CARD_OF_LEVEL_1_26', 1, 0, new CardToken({ white: 1, black: 1, blue: 1 }), new CardToken({ green: 1 })),
  new DevelopmentCard(27, 'CARD_OF_LEVEL_1_27', 1, 0, new CardToken({ white: 1, green: 1, red: 1 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(28, 'CARD_OF_LEVEL_1_28', 1, 0, new CardToken({ black: 2, red: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(29, 'CARD_OF_LEVEL_1_29', 1, 0, new CardToken({ green: 1, blue: 2 }), new CardToken({ red: 1 })),
  new DevelopmentCard(30, 'CARD_OF_LEVEL_1_30', 1, 1, new CardToken({ green: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(31, 'CARD_OF_LEVEL_1_31', 1, 1, new CardToken({ blue: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(32, 'CARD_OF_LEVEL_1_32', 1, 1, new CardToken({ white: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(33, 'CARD_OF_LEVEL_1_33', 1, 1, new CardToken({ red: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(34, 'CARD_OF_LEVEL_1_34', 1, 1, new CardToken({ black: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(35, 'CARD_OF_LEVEL_1_35', 1, 0, new CardToken({ blue: 1, red: 1 }), new CardToken({ green: 1 })),
  new DevelopmentCard(36, 'CARD_OF_LEVEL_1_36', 1, 0, new CardToken({ red: 1, black: 1, white: 1 }), new CardToken({ white: 1 })),
  new DevelopmentCard(37, 'CARD_OF_LEVEL_1_37', 1, 0, new CardToken({ black: 2, blue: 1 }), new CardToken({ black: 1 })),
  new DevelopmentCard(38, 'CARD_OF_LEVEL_1_38', 1, 0, new CardToken({ green: 1, black: 2 }), new CardToken({ green: 1 })),
  new DevelopmentCard(39, 'CARD_OF_LEVEL_1_39', 1, 0, new CardToken({ blue: 2, white: 1 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(40, 'CARD_OF_LEVEL_1_40', 1, 1, new CardToken({ red: 4 }), new CardToken({ red: 1 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_2: DevelopmentCard[] = [
  new DevelopmentCard(41, 'CARD_OD_LEVEL_2_1', 2, 1, new CardToken({ red: 5 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(42, 'CARD_OD_LEVEL_2_2', 2, 2, new CardToken({ green: 5 }), new CardToken({ black: 1 })),
  new DevelopmentCard(43, 'CARD_OD_LEVEL_2_3', 2, 2, new CardToken({ white: 5 }), new CardToken({ red: 1 })),
  new DevelopmentCard(44, 'CARD_OD_LEVEL_2_4', 2, 1, new CardToken({ black: 6 }), new CardToken({ green: 1 })),
  new DevelopmentCard(45, 'CARD_OD_LEVEL_2_5', 2, 2, new CardToken({ blue: 5 }), new CardToken({ white: 1 })),
  new DevelopmentCard(46, 'CARD_OD_LEVEL_2_6', 2, 1, new CardToken({ white: 3, red: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(47, 'CARD_OD_LEVEL_2_7', 2, 2, new CardToken({ black: 4, red: 2 }), new CardToken({ red: 1 })),
  new DevelopmentCard(48, 'CARD_OD_LEVEL_2_8', 2, 2, new CardToken({ green: 5, blue: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(49, 'CARD_OD_LEVEL_2_9', 2, 1, new CardToken({ blue: 3, green: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(50, 'CARD_OD_LEVEL_2_10', 2, 1, new CardToken({ green: 6 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(51, 'CARD_OD_LEVEL_2_11', 2, 2, new CardToken({ red: 5, white: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(52, 'CARD_OD_LEVEL_2_12', 2, 1, new CardToken({ black: 3, white: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(53, 'CARD_OD_LEVEL_2_13', 2, 2, new CardToken({ blue: 5, green: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(54, 'CARD_OD_LEVEL_2_14', 2, 1, new CardToken({ white: 5, red: 2 }), new CardToken({ black: 1 })),
  new DevelopmentCard(55, 'CARD_OD_LEVEL_2_15', 2, 3, new CardToken({ black: 7 }), new CardToken({ black: 1 })),
  new DevelopmentCard(56, 'CARD_OD_LEVEL_2_16', 2, 2, new CardToken({ green: 6, blue: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(57, 'CARD_OD_LEVEL_2_17', 2, 2, new CardToken({ red: 5, black: 2 }), new CardToken({ white: 1 })),
  new DevelopmentCard(58, 'CARD_OD_LEVEL_2_18', 2, 3, new CardToken({ white: 7 }), new CardToken({ green: 1 })),
  new DevelopmentCard(59, 'CARD_OD_LEVEL_2_19', 2, 2, new CardToken({ red: 5, blue: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(60, 'CARD_OD_LEVEL_2_20', 2, 2, new CardToken({ green: 5, black: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(61, 'CARD_OD_LEVEL_2_21', 2, 3, new CardToken({ green: 7 }), new CardToken({ green: 1 })),
  new DevelopmentCard(62, 'CARD_OD_LEVEL_2_22', 2, 2, new CardToken({ black: 6, red: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(63, 'CARD_OD_LEVEL_2_23', 2, 3, new CardToken({ blue: 7 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(64, 'CARD_OD_LEVEL_2_24', 2, 2, new CardToken({ red: 5, white: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(65, 'CARD_OD_LEVEL_2_25', 2, 3, new CardToken({ red: 7 }), new CardToken({ red: 1 })),
  new DevelopmentCard(66, 'CARD_OD_LEVEL_2_26', 2, 2, new CardToken({ white: 5, blue: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(67, 'CARD_OD_LEVEL_2_27', 2, 3, new CardToken({ black: 7 }), new CardToken({ black: 1 })),
  new DevelopmentCard(68, 'CARD_OD_LEVEL_2_28', 2, 2, new CardToken({ green: 5, white: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(69, 'CARD_OD_LEVEL_2_29', 2, 3, new CardToken({ black: 7 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(70, 'CARD_OD_LEVEL_2_30', 2, 2, new CardToken({ blue: 6, red: 3 }), new CardToken({ blue: 1 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_3: DevelopmentCard[] = [
  new DevelopmentCard(71, 'CARD_OF_LEVEL_3_1', 3, 4, new CardToken({ black: 7, red: 3, green: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(72, 'CARD_OF_LEVEL_3_2', 3, 4, new CardToken({ white: 7, blue: 3, red: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(73, 'CARD_OF_LEVEL_3_3', 3, 5, new CardToken({ green: 7, black: 3, blue: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(74, 'CARD_OF_LEVEL_3_4', 3, 4, new CardToken({ blue: 7, white: 3, green: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(75, 'CARD_OF_LEVEL_3_5', 3, 5, new CardToken({ red: 7, black: 3, white: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(76, 'CARD_OF_LEVEL_3_6', 3, 4, new CardToken({ green: 7, red: 3, blue: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(77, 'CARD_OF_LEVEL_3_7', 3, 4, new CardToken({ black: 7, white: 3, blue: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(78, 'CARD_OF_LEVEL_3_8', 3, 5, new CardToken({ red: 7, green: 3, black: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(79, 'CARD_OF_LEVEL_3_9', 3, 4, new CardToken({ white: 7, green: 3, black: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(80, 'CARD_OF_LEVEL_3_10', 3, 5, new CardToken({ blue: 7, red: 3, green: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(81, 'CARD_OF_LEVEL_3_11', 3, 4, new CardToken({ black: 7, blue: 3, white: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(82, 'CARD_OF_LEVEL_3_12', 3, 4, new CardToken({ white: 7, red: 3, green: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(83, 'CARD_OF_LEVEL_3_13', 3, 5, new CardToken({ blue: 7, black: 3, red: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(84, 'CARD_OF_LEVEL_3_14', 3, 4, new CardToken({ green: 7, white: 3, red: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(85, 'CARD_OF_LEVEL_3_15', 3, 5, new CardToken({ black: 7, blue: 3, green: 3 }), new CardToken({ green: 1 })),
  new DevelopmentCard(86, 'CARD_OF_LEVEL_3_16', 3, 4, new CardToken({ white: 7, black: 3, blue: 3 }), new CardToken({ white: 1 })),
  new DevelopmentCard(87, 'CARD_OF_LEVEL_3_17', 3, 4, new CardToken({ red: 7, green: 3, blue: 3 }), new CardToken({ blue: 1 })),
  new DevelopmentCard(88, 'CARD_OF_LEVEL_3_18', 3, 5, new CardToken({ green: 7, black: 3, red: 3 }), new CardToken({ black: 1 })),
  new DevelopmentCard(89, 'CARD_OF_LEVEL_3_19', 3, 4, new CardToken({ blue: 7, red: 3, white: 3 }), new CardToken({ red: 1 })),
  new DevelopmentCard(90, 'CARD_OF_LEVEL_3_20', 3, 5, new CardToken({ black: 7, green: 3, white: 3 }), new CardToken({ white: 1 })),
];
