import { CardToken, DevelopmentCard, NobleCard } from './classes';

export const NOBLE_CARDS: NobleCard[] = [
  new NobleCard(1, 3, new CardToken({ sapphire: 4, diamond: 4 })),
  new NobleCard(2, 3, new CardToken({ sapphire: 4, emerald: 4 })),
  new NobleCard(3, 3, new CardToken({ ruby: 4, emerald: 4 })),
  new NobleCard(4, 3, new CardToken({ onyx: 4, ruby: 4 })),
  new NobleCard(5, 3, new CardToken({ onyx: 4, diamond: 4 })),
  new NobleCard(6, 3, new CardToken({ onyx: 3, sapphire: 3, diamond: 3 })),
  new NobleCard(7, 3, new CardToken({ emerald: 3, sapphire: 3, diamond: 3 })),
  new NobleCard(8, 3, new CardToken({ emerald: 3, sapphire: 3, ruby: 3 })),
  new NobleCard(9, 3, new CardToken({ onyx: 3, ruby: 3, emerald: 3 })),
  new NobleCard(10, 3, new CardToken({ onyx: 3, ruby: 3, diamond: 3 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_1: DevelopmentCard[] = [
  new DevelopmentCard(1, 1, 1, new CardToken({ emerald: 4 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(2, 1, 1, new CardToken({ ruby: 4 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(3, 1, 1, new CardToken({ onyx: 4 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(4, 1, 1, new CardToken({ diamond: 4 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(5, 1, 1, new CardToken({ sapphire: 4 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(6, 1, 0, new CardToken({ diamond: 3, sapphire: 1, onyx: 1 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(7, 1, 0, new CardToken({ sapphire: 1, emerald: 3, ruby: 1 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(8, 1, 0, new CardToken({ diamond: 1, sapphire: 3, emerald: 1 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(9, 1, 0, new CardToken({ diamond: 1, ruby: 1, onyx: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(10, 1, 0, new CardToken({ emerald: 1, ruby: 3, onyx: 1 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(11, 1, 0, new CardToken({ sapphire: 3 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(12, 1, 0, new CardToken({ onyx: 3 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(13, 1, 0, new CardToken({ ruby: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(14, 1, 0, new CardToken({ diamond: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(15, 1, 0, new CardToken({ emerald: 3 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(16, 1, 0, new CardToken({ sapphire: 2, emerald: 2, onyx: 1 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(17, 1, 0, new CardToken({ diamond: 1, emerald: 2, ruby: 2 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(18, 1, 0, new CardToken({ sapphire: 1, ruby: 2, onyx: 2 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(19, 1, 0, new CardToken({ diamond: 2, emerald: 1, onyx: 2 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(20, 1, 0, new CardToken({ diamond: 2, sapphire: 2, ruby: 1 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(21, 1, 0, new CardToken({ sapphire: 2, onyx: 2 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(22, 1, 0, new CardToken({ emerald: 2, onyx: 2 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(23, 1, 0, new CardToken({ sapphire: 2, ruby: 2 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(24, 1, 0, new CardToken({ diamond: 2, ruby: 2 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(25, 1, 0, new CardToken({ diamond: 2, emerald: 2 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(26, 1, 0, new CardToken({ sapphire: 1, emerald: 2, ruby: 1, onyx: 1 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(27, 1, 0, new CardToken({ diamond: 1, emerald: 1, ruby: 2, onyx: 1 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(28, 1, 0, new CardToken({ diamond: 1, sapphire: 1, ruby: 1, onyx: 2 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(29, 1, 0, new CardToken({ diamond: 2, sapphire: 1, emerald: 1, onyx: 1 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(30, 1, 0, new CardToken({ diamond: 1, sapphire: 2, emerald: 1, ruby: 1 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(31, 1, 0, new CardToken({ ruby: 2, onyx: 1 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(32, 1, 0, new CardToken({ diamond: 1, onyx: 2 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(33, 1, 0, new CardToken({ diamond: 2, sapphire: 1 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(34, 1, 0, new CardToken({ sapphire: 2, emerald: 1 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(35, 1, 0, new CardToken({ emerald: 2, ruby: 1 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(36, 1, 0, new CardToken({ sapphire: 1, emerald: 1, ruby: 1, onyx: 1 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(37, 1, 0, new CardToken({ diamond: 1, emerald: 1, ruby: 1, onyx: 1 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(38, 1, 0, new CardToken({ diamond: 1, sapphire: 1, ruby: 1, onyx: 1 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(39, 1, 0, new CardToken({ diamond: 1, sapphire: 1, emerald: 1, onyx: 1 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(40, 1, 0, new CardToken({ diamond: 1, sapphire: 1, emerald: 1, ruby: 1 }), new CardToken({ onyx: 1 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_2: DevelopmentCard[] = [
  new DevelopmentCard(41, 2, 1, new CardToken({ emerald: 3, ruby: 2, onyx: 2 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(42, 2, 1, new CardToken({ sapphire: 2, emerald: 2, ruby: 3 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(43, 2, 1, new CardToken({ diamond: 2, sapphire: 3, onyx: 2 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(44, 2, 1, new CardToken({ diamond: 2, ruby: 2, onyx: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(45, 2, 1, new CardToken({ diamond: 3, sapphire: 2, emerald: 2 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(46, 2, 1, new CardToken({ diamond: 2, sapphire: 3, ruby: 3 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(47, 2, 1, new CardToken({ sapphire: 2, emerald: 3, onyx: 3 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(48, 2, 1, new CardToken({ diamond: 3, emerald: 2, ruby: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(49, 2, 1, new CardToken({ sapphire: 3, ruby: 2, onyx: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(50, 2, 1, new CardToken({ diamond: 3, emerald: 3, onyx: 2 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(51, 2, 3, new CardToken({ diamond: 6 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(52, 2, 3, new CardToken({ sapphire: 6 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(53, 2, 3, new CardToken({ emerald: 6 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(54, 2, 3, new CardToken({ ruby: 6 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(55, 2, 3, new CardToken({ onyx: 6 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(56, 2, 2, new CardToken({ emerald: 1, ruby: 4, onyx: 2 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(57, 2, 2, new CardToken({ diamond: 2, ruby: 1, onyx: 4 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(58, 2, 2, new CardToken({ diamond: 4, sapphire: 2, onyx: 1 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(59, 2, 2, new CardToken({ diamond: 1, sapphire: 4, emerald: 2 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(60, 2, 2, new CardToken({ sapphire: 1, emerald: 4, ruby: 2 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(61, 2, 2, new CardToken({ ruby: 5 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(62, 2, 2, new CardToken({ sapphire: 5 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(63, 2, 2, new CardToken({ emerald: 5 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(64, 2, 2, new CardToken({ onyx: 5 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(65, 2, 2, new CardToken({ diamond: 5 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(66, 2, 2, new CardToken({ ruby: 5, onyx: 3 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(67, 2, 2, new CardToken({ diamond: 5, sapphire: 3 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(68, 2, 2, new CardToken({ sapphire: 5, emerald: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(69, 2, 2, new CardToken({ diamond: 3, onyx: 5 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(70, 2, 2, new CardToken({ emerald: 5, ruby: 3 }), new CardToken({ onyx: 1 })),
];

export const DEVELOPMENT_CARDS_OF_LEVEL_3: DevelopmentCard[] = [
  new DevelopmentCard(71, 3, 3, new CardToken({ sapphire: 3, emerald: 3, ruby: 5, onyx: 3 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(72, 3, 3, new CardToken({ diamond: 3, emerald: 3, ruby: 3, onyx: 5 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(73, 3, 3, new CardToken({ diamond: 5, sapphire: 3, ruby: 3, onyx: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(74, 3, 3, new CardToken({ diamond: 3, sapphire: 5, emerald: 3, onyx: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(75, 3, 3, new CardToken({ diamond: 3, sapphire: 3, emerald: 5, ruby: 3 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(76, 3, 4, new CardToken({ onyx: 7 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(77, 3, 4, new CardToken({ diamond: 7 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(78, 3, 4, new CardToken({ sapphire: 7 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(79, 3, 4, new CardToken({ emerald: 7 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(80, 3, 4, new CardToken({ ruby: 7 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(81, 3, 4, new CardToken({ diamond: 3, ruby: 3, onyx: 6 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(82, 3, 4, new CardToken({ diamond: 6, sapphire: 3, onyx: 6 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(83, 3, 4, new CardToken({ diamond: 3, sapphire: 6, emerald: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(84, 3, 4, new CardToken({ sapphire: 3, emerald: 6, ruby: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(85, 3, 4, new CardToken({ sapphire: 3, emerald: 6, ruby: 3 }), new CardToken({ onyx: 1 })),
  new DevelopmentCard(86, 3, 5, new CardToken({ diamond: 3, onyx: 7 }), new CardToken({ diamond: 1 })),
  new DevelopmentCard(87, 3, 5, new CardToken({ diamond: 7, sapphire: 3 }), new CardToken({ sapphire: 1 })),
  new DevelopmentCard(88, 3, 5, new CardToken({ sapphire: 7, emerald: 3 }), new CardToken({ emerald: 1 })),
  new DevelopmentCard(89, 3, 5, new CardToken({ emerald: 7, ruby: 3 }), new CardToken({ ruby: 1 })),
  new DevelopmentCard(90, 3, 5, new CardToken({ ruby: 7, onyx: 3 }), new CardToken({ onyx: 1 })),
];
